using Vitality.Models.Repos.Services.Auth;
using Xunit;

namespace Vitality.Models.Tests;

/// <summary>
/// Guards the one thing a BCrypt.Net-Next version bump can silently break:
/// whether passwords already in the database still let their owners log in.
///
/// Until TEL-48, Vitality.Models pinned BCrypt.Net-Next 0.1.0 — a version that
/// has never been published on nuget.org. A PackageReference version is a
/// MINIMUM constraint, so every restore floated up to the nearest real release
/// (2.0.0) and emitted NU1603. TEL-48 pins 4.0.3 instead, which is a major
/// version change for the library that hashes passwords.
///
/// The hashes below are not hand-written. They were produced by
/// BCrypt.Net-Next 2.0.0 — the version that was actually restoring, and
/// therefore the version that produced whatever is in the deployed database —
/// via BCrypt.Net.BCrypt.HashPassword(password, 12), matching
/// PasswordHasher.WorkFactor. They stand in for real stored credentials.
///
/// If a future upgrade changes the hash format, the work factor interpretation,
/// or the string encoding, these assertions fail here rather than at the login
/// page.
/// </summary>
public class PasswordHasherCompatibilityTests
{
    private readonly PasswordHasher _hasher = new();

    /// <summary>
    /// password -> hash of that password, generated by BCrypt.Net-Next 2.0.0 at
    /// work factor 12. Covers a passphrase with spaces, punctuation, a
    /// single character, non-ASCII, and 71 characters (just under bcrypt's
    /// 72-byte input limit).
    /// </summary>
    [Theory]
    [InlineData("correct horse battery staple", "$2a$12$esQfyW2HnYvaVRepp6ljeuTnQ5T4uo4Dvab/m/h6wArZayRmMdn5.")]
    [InlineData("P@ssw0rd!", "$2a$12$xq8h4sYyNQCULWXMlYwmhOTEv8jvE/cWBWsn5IsSZXc4yBImW74XK")]
    [InlineData("short", "$2a$12$0lCue35JAnNEAwI6YCXsbuR8d/VCbxLjkuX9i5xrxnWHAo8EE36E6")]
    [InlineData("a", "$2a$12$3ya3pocEHIoUn8xPWuw6meGwqoGDdYL1kOOvDBVGAFc8dLWEH7ona")]
    [InlineData("ünïcødé-påss-🔐", "$2a$12$.oKW/.tGjqNllR6ziWUJgeyJYO38XSvTljBGi9MRK9VUl2DlYZ71a")]
    [InlineData("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
                "$2a$12$tQbcRv7Ak8p5/rK1FZoKrOVoYNUQ/jRtF27IN6.Zvdbqi./Yj9aMO")]
    public void VerifyPassword_accepts_hashes_written_by_BCrypt_2_0_0(string password, string legacyHash) =>
        Assert.True(_hasher.VerifyPassword(password, legacyHash),
            "A password hashed by the previously restored BCrypt.Net-Next 2.0.0 no longer verifies. " +
            "Shipping this would lock out every existing user.");

    [Theory]
    [InlineData("correct horse battery staple", "$2a$12$esQfyW2HnYvaVRepp6ljeuTnQ5T4uo4Dvab/m/h6wArZayRmMdn5.")]
    [InlineData("P@ssw0rd!", "$2a$12$xq8h4sYyNQCULWXMlYwmhOTEv8jvE/cWBWsn5IsSZXc4yBImW74XK")]
    [InlineData("a", "$2a$12$3ya3pocEHIoUn8xPWuw6meGwqoGDdYL1kOOvDBVGAFc8dLWEH7ona")]
    public void VerifyPassword_still_rejects_the_wrong_password_against_a_2_0_0_hash(string password, string legacyHash)
    {
        Assert.False(_hasher.VerifyPassword(password + "X", legacyHash));
        Assert.False(_hasher.VerifyPassword(password.ToUpperInvariant() + "_", legacyHash));
    }

    [Fact]
    public void HashPassword_still_emits_the_2a_prefix_and_work_factor_12()
    {
        var hash = _hasher.HashPassword("correct horse battery staple");

        // A change here means newly written hashes stop matching the format the
        // rest of the system assumes — including PasswordHasher.IsHashed and any
        // stored-credential migration that sniffs the prefix.
        Assert.StartsWith("$2a$12$", hash);
        Assert.True(_hasher.IsHashed(hash));
    }

    [Fact]
    public void HashPassword_round_trips_through_VerifyPassword()
    {
        const string password = "correct horse battery staple";

        var hash = _hasher.HashPassword(password);

        Assert.True(_hasher.VerifyPassword(password, hash));
        Assert.False(_hasher.VerifyPassword(password + "X", hash));
    }

    [Fact]
    public void HashPassword_salts_so_two_hashes_of_one_password_differ()
    {
        const string password = "correct horse battery staple";

        Assert.NotEqual(_hasher.HashPassword(password), _hasher.HashPassword(password));
    }
}
